Repository open-company/open-company-auth, pull requests merged in 2018-10, with the labels that each got.

#62 Allow us to easily use the REPL for DB access only
  project.clj
  src/dev.clj
  src/oc/auth/components.clj
  src/oc/auth/lib/google.clj
Labels: ready for deploy

#61 Strip tags on invite note
  project.clj
  src/oc/auth/lib/sqs.clj
Labels: ready for deploy

#63 Add slack bot info to user when authenticating with google.
  src/oc/auth/api/google.clj
  src/oc/auth/api/users.clj
Labels: reviewing

#64 Upgrade oc lib to fix xss strip function.
  project.clj
Labels: URGENT, ready for review

#65 Default avatar url if avatar url is empty.
  src/oc/auth/resources/user.clj
Labels: ready for deploy
