Repository open-company/open-company-auth, pull requests merged in 2018-03, with the labels that each got.

#28 Private invite notification
  REPL_notes.clj
  project.clj
  src/oc/auth/api/teams.clj
Labels: ready for deploy

#30 Fix the activate of a user on Slack auth (was there, but broken).
  project.clj
  src/oc/auth/api/slack.clj
Labels: reviewing

#31 Fix admin link
  project.clj
  src/oc/auth/representations/user.clj
Labels: URGENT, reviewing
