Repository open-company/open-company-auth, pull requests merged in 2018-12, with the labels that each got.

#69 Storage lib
  project.clj
  src/oc/auth/api/users.clj
Labels: ready for deploy

#70 Decode the id token on the API entry request.
  project.clj
  src/oc/auth/api/entry_point.clj
Labels: reviewing

#71 Post link behaviour
  project.clj
  src/oc/auth/api/entry_point.clj
  src/oc/auth/api/teams.clj
  src/oc/auth/representations/user.clj
Labels: ready for deploy

#72 Fix decode id-token
  project.clj
Labels: ready for review
