Repository open-company/open-company-auth, pull requests merged in 2018-04, with the labels that each got.

#34 Invite logo
  src/oc/auth/api/teams.clj
  src/oc/auth/lib/sqs.clj
  src/oc/auth/resources/team.clj
Labels: ready for deploy

#33 Need additional scope for slack to read urls.
  src/oc/auth/config.clj
Labels: reviewing

#36 Add missing keys for the slack invite.
  src/oc/auth/lib/sqs.clj
Labels: URGENT, ready for deploy

#37 Delay verify email
  src/oc/auth/api/users.clj
  src/oc/auth/lib/sqs.clj
Labels: reviewing

#39 add note to sqs payload
  src/oc/auth/lib/sqs.clj
Labels: ready for review
