Repository open-company/open-company-auth, pull requests merged in 2018-05, with the labels that each got.

#40 De-dupe teams coming from Slack and email matches.
  project.clj
  src/oc/auth/resources/user.clj
Labels: URGENT, reviewing

#43 Slack unfurl support.
  project.clj
  src/oc/auth/api/users.clj
  src/oc/auth/db/migrations/1524079657092_user_slack_team_id.edn
  src/oc/auth/resources/user.clj
Labels: ready for deploy

#42 Settings restyle
  src/oc/auth/api/slack.clj
  src/oc/auth/representations/team.clj
  src/oc/auth/resources/slack_org.clj
Labels: ready for deploy

#44 Handle the app removal event from Slack.
  src/dev.clj
  src/oc/auth/api/teams.clj
  src/oc/auth/app.clj
  src/oc/auth/async/slack_router.clj
  src/oc/auth/components.clj
  src/oc/auth/config.clj
Labels: ready for deploy

#45 Slack welcome message after installing the bot.
  README.md
  project.clj
  src/oc/auth/api/slack.clj
  src/oc/auth/app.clj
  src/oc/auth/lib/sqs.clj
Labels: ready for deploy

#47 Read only email
  src/oc/auth/resources/user.clj
Labels: ready for review

#46 Slack notification step
  src/oc/auth/api/slack.clj
Labels: ready for deploy
